# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test01SEIRespostaConfigs():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://seleniumhub:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_00ConfigValidacaoSistema(self):
    self.driver.get("http://sei.resposta.nuvem.gov.br//sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//ul[@id=\'main-menu\']/li/a")))
    self.driver.find_element(By.XPATH, "//ul[@id=\'main-menu\']/li/a").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//*[text()=\"Módulo de Resposta - Gov.br\"]")))
    self.driver.find_element(By.XPATH, "//*[text()=\"Módulo de Resposta - Gov.br\"]").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.LINK_TEXT, "Parâmetros de Configuração")))
    self.driver.find_element(By.LINK_TEXT, "Parâmetros de Configuração").click()
    self.driver.find_element(By.NAME, "sbmSalvar").click()
    assert self.driver.switch_to.alert.text == "Selecione o Sistema."
    self.driver.switch_to.alert.accept()
  
  def test_01ConfigValidacaoProcesso(self):
    self.driver.get("http://sei.resposta.nuvem.gov.br//sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//ul[@id=\'main-menu\']/li/a")))
    self.driver.find_element(By.XPATH, "//ul[@id=\'main-menu\']/li/a").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//*[text()=\"Módulo de Resposta - Gov.br\"]")))
    self.driver.find_element(By.XPATH, "//*[text()=\"Módulo de Resposta - Gov.br\"]").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.LINK_TEXT, "Parâmetros de Configuração")))
    self.driver.find_element(By.LINK_TEXT, "Parâmetros de Configuração").click()
    self.driver.find_element(By.ID, "selSistema").click()
    dropdown = self.driver.find_element(By.ID, "selSistema")
    dropdown.find_element(By.XPATH, "//option[. = 'PD_GOV_BR']").click()
    self.driver.find_element(By.NAME, "sbmSalvar").click()
    assert self.driver.switch_to.alert.text == "Selecione o Tipo de Processo."
    self.driver.switch_to.alert.accept()
  
  def test_02ConfigValidacaoDocumento(self):
    self.driver.get("http://sei.resposta.nuvem.gov.br//sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//ul[@id=\'main-menu\']/li/a")))
    self.driver.find_element(By.XPATH, "//ul[@id=\'main-menu\']/li/a").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//*[text()=\"Módulo de Resposta - Gov.br\"]")))
    self.driver.find_element(By.XPATH, "//*[text()=\"Módulo de Resposta - Gov.br\"]").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.LINK_TEXT, "Parâmetros de Configuração")))
    self.driver.find_element(By.LINK_TEXT, "Parâmetros de Configuração").click()
    self.driver.find_element(By.ID, "selSistema").click()
    dropdown = self.driver.find_element(By.ID, "selSistema")
    dropdown.find_element(By.XPATH, "//option[. = 'PD_GOV_BR']").click()
    dropdown = self.driver.find_element(By.ID, "selTipoProcesso")
    dropdown.find_element(By.XPATH, "//option[. = 'Protocolização de documentos para o Protocolo Central do ME']").click()
    self.driver.find_element(By.NAME, "sbmSalvar").click()
    assert self.driver.switch_to.alert.text == "Selecione o Tipo de Documento."
    self.driver.switch_to.alert.accept()
  
  def test_03ConfigConfirmacao(self):
    self.driver.get("http://sei.resposta.nuvem.gov.br//sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//ul[@id=\'main-menu\']/li/a")))
    self.driver.find_element(By.XPATH, "//ul[@id=\'main-menu\']/li/a").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//*[text()=\"Módulo de Resposta - Gov.br\"]")))
    self.driver.find_element(By.XPATH, "//*[text()=\"Módulo de Resposta - Gov.br\"]").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.LINK_TEXT, "Parâmetros de Configuração")))
    self.driver.find_element(By.LINK_TEXT, "Parâmetros de Configuração").click()
    self.driver.find_element(By.ID, "selSistema").click()
    dropdown = self.driver.find_element(By.ID, "selSistema")
    dropdown.find_element(By.XPATH, "//option[. = 'PD_GOV_BR']").click()
    dropdown = self.driver.find_element(By.ID, "selTipoProcesso")
    dropdown.find_element(By.XPATH, "//option[. = 'Protocolização de documentos para o Protocolo Central do ME']").click()
    dropdown = self.driver.find_element(By.ID, "selTipoDocumento")
    dropdown.find_element(By.XPATH, "//option[. = 'Resposta ao Protocolo Digital']").click()
    self.driver.find_element(By.ID, "selTipoDocumento").click()
    self.driver.find_element(By.NAME, "sbmSalvar").click()
    time.sleep(2000)
    self.driver.switch_to.alert.accept()
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "selTipoProcesso")))
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//ul[@id=\'main-menu\']/li/a")))
    self.driver.find_element(By.XPATH, "//ul[@id=\'main-menu\']/li/a").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//*[text()=\"Módulo de Resposta - Gov.br\"]")))
    self.driver.find_element(By.XPATH, "//*[text()=\"Módulo de Resposta - Gov.br\"]").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.LINK_TEXT, "Parâmetros de Configuração")))
    self.driver.find_element(By.LINK_TEXT, "Parâmetros de Configuração").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "selTipoProcesso")))
    element = self.driver.find_element(By.ID, "selTipoDocumento")
    locator = "option[@value='{}']".format(element.get_attribute("value"))
    selected_text = element.find_element(By.XPATH, locator).text
    assert selected_text == "Resposta ao Protocolo Digital"
  
