# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test01SEIRespostaConfigs():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://seleniumhub:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_00ConfigValidacaoSistema(self):
    self.driver.get("http://sei.resposta.nuvem.gov.br/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//*[@id=\"main-menu\"]/li[1]/a")))
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[1]/a").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//*[@id=\"main-menu\"]/li[1]/ul/li[11]/a")))
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[1]/ul/li[11]/a").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//*[@id=\"main-menu\"]/li[1]/ul/li[11]/ul/li/a")))
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[1]/ul/li[11]/ul/li/a").click()
    self.driver.find_element(By.NAME, "sbmSalvar").click()
    assert self.driver.switch_to.alert.text == "Selecione o Sistema."
    self.driver.switch_to.alert.accept()
  
  def test_01ConfigValidacaoProcesso(self):
    self.driver.get("http://sei.resposta.nuvem.gov.br/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//*[@id=\"main-menu\"]/li[1]/a")))
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[1]/a").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//*[@id=\"main-menu\"]/li[1]/ul/li[11]/a")))
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[1]/ul/li[11]/a").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//*[@id=\"main-menu\"]/li[1]/ul/li[11]/ul/li/a")))
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[1]/ul/li[11]/ul/li/a").click()
    self.driver.find_element(By.ID, "selSistema").click()
    dropdown = self.driver.find_element(By.ID, "selSistema")
    dropdown.find_element(By.XPATH, "//option[. = 'PD_GOV_BR']").click()
    self.driver.find_element(By.NAME, "sbmSalvar").click()
    assert self.driver.switch_to.alert.text == "Selecione o Tipo de Processo."
    self.driver.switch_to.alert.accept()
  
  def test_02ConfigValidacaoDocumento(self):
    self.driver.get("http://sei.resposta.nuvem.gov.br/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//*[@id=\"main-menu\"]/li[1]/a")))
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[1]/a").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//*[@id=\"main-menu\"]/li[1]/ul/li[11]/a")))
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[1]/ul/li[11]/a").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//*[@id=\"main-menu\"]/li[1]/ul/li[11]/ul/li/a")))
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[1]/ul/li[11]/ul/li/a").click()
    self.driver.find_element(By.ID, "selSistema").click()
    dropdown = self.driver.find_element(By.ID, "selSistema")
    dropdown.find_element(By.XPATH, "//option[. = 'PD_GOV_BR']").click()
    dropdown = self.driver.find_element(By.ID, "selTipoProcesso")
    dropdown.find_element(By.XPATH, "//option[. = 'Acesso à Informação: Demanda do e-SIC']").click()
    self.driver.find_element(By.NAME, "sbmSalvar").click()
    assert self.driver.switch_to.alert.text == "Selecione o Tipo de Documento."
    self.driver.switch_to.alert.accept()
  
  def test_03ConfigConfirmacao(self):
    self.driver.get("http://sei.resposta.nuvem.gov.br/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//*[@id=\"main-menu\"]/li[1]/a")))
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[1]/a").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//*[@id=\"main-menu\"]/li[1]/ul/li[11]/a")))
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[1]/ul/li[11]/a").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//*[@id=\"main-menu\"]/li[1]/ul/li[11]/ul/li/a")))
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[1]/ul/li[11]/ul/li/a").click()
    self.driver.find_element(By.ID, "selSistema").click()
    dropdown = self.driver.find_element(By.ID, "selSistema")
    dropdown.find_element(By.XPATH, "//option[. = 'PD_GOV_BR']").click()
    dropdown = self.driver.find_element(By.ID, "selTipoProcesso")
    dropdown.find_element(By.XPATH, "//option[. = 'Acesso à Informação: Demanda do e-SIC']").click()
    dropdown = self.driver.find_element(By.ID, "selTipoDocumento")
    dropdown.find_element(By.XPATH, "//option[. = 'Resposta ao Protocolo Digital']").click()
    self.driver.find_element(By.ID, "selTipoDocumento").click()
    self.driver.find_element(By.NAME, "sbmSalvar").click()
    assert self.driver.switch_to.alert.text == "Mapeamento cadastrado com sucesso."
    self.driver.switch_to.alert.accept()
  
