# Generated by Selenium IDE
# -*- coding: utf-8 -*-
import pytest
import os
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test00SEIRespostaCriarSistema():
  def setup_method(self, method):
    if ("LOCAL" == os.environ["SELENIUMTEST_MODALIDADE"]):
        self.driver = webdriver.Chrome()
    else:
        self.driver = webdriver.Remote(command_executor=os.environ["SELENIUMTEST_SELENIUMHOST_URL"], desired_capabilities=DesiredCapabilities.CHROME)
        
    if ((not 'maximizar_screen' in os.environ) or os.environ['maximizar_screen'] == 'true'):
        self.driver.maximize_window()
        
    self.driver.implicitly_wait(5)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_criarSistema(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmAcessar").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Administração\"]").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Sistemas\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Novo").click()
    dropdown = self.driver.find_element(By.ID, "selOrgao")
    dropdown.find_element(By.XPATH, "//option[. = '"+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"']").click()
    self.driver.find_element(By.ID, "selOrgao").click()
    self.driver.find_element(By.ID, "txtSigla").click()
    self.driver.find_element(By.ID, "txtSigla").send_keys("PD_GOV_BR")
    self.driver.find_element(By.ID, "txtNome").send_keys("Protocolo Digital")
    self.driver.find_element(By.NAME, "sbmCadastrarSistema").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Administração\"]").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Sistemas\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Listar").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[4]/td[6]/a[1]").click()
    self.driver.find_element(By.CSS_SELECTOR, "#btnNovo > .infraTeclaAtalho").click()
    self.driver.find_element(By.ID, "txtIdentificacao").send_keys("SeiResposta")
    self.driver.find_element(By.ID, "txtDescricao").send_keys("Resposta ao protoloco digital")
    self.driver.find_element(By.XPATH, "//div[@id=\'divChkSinServidor\']/div/label").click()
    self.driver.find_element(By.ID, "txtServidor").click()
    self.driver.find_element(By.ID, "txtServidor").send_keys("*")
    self.driver.find_element(By.ID, "txtServidor").send_keys(Keys.ENTER)
    self.driver.find_element(By.NAME, "sbmCadastrarServico").click()
    self.driver.find_element(By.XPATH, "//img[@title=\'Operações\']").click()
    self.driver.find_element(By.ID, "btnNovo").click()
    dropdown = self.driver.find_element(By.ID, "selStaOperacaoServico")
    dropdown.find_element(By.XPATH, "//option[. = 'Consultar Processo']").click()
    self.driver.find_element(By.NAME, "sbmCadastrarOperacaoServico").click()
    self.driver.find_element(By.ID, "btnNovo").click()
    dropdown = self.driver.find_element(By.ID, "selStaOperacaoServico")
    dropdown.find_element(By.XPATH, "//option[. = 'Enviar Processo']").click()
    self.driver.find_element(By.NAME, "sbmCadastrarOperacaoServico").click()
    self.driver.find_element(By.ID, "btnNovo").click()
    dropdown = self.driver.find_element(By.ID, "selStaOperacaoServico")
    dropdown.find_element(By.XPATH, "//option[. = 'Gerar Processo']").click()
    self.driver.find_element(By.NAME, "sbmCadastrarOperacaoServico").click()
    self.driver.find_element(By.ID, "btnNovo").click()
    dropdown = self.driver.find_element(By.ID, "selStaOperacaoServico")
    dropdown.find_element(By.XPATH, "//option[. = 'Incluir Documento']").click()
    self.driver.find_element(By.NAME, "sbmCadastrarOperacaoServico").click()
    self.driver.find_element(By.ID, "btnNovo").click()
    dropdown = self.driver.find_element(By.ID, "selStaOperacaoServico")
    dropdown.find_element(By.XPATH, "//option[. = 'Consultar Documento']").click()
    self.driver.find_element(By.NAME, "sbmCadastrarOperacaoServico").click()
    self.driver.find_element(By.ID, "btnFechar").click()
    self.driver.find_element(By.ID, "btnFechar").click()
  
  def test_criarTipoDocumento(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmAcessar").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Administração\"]").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Tipos de Documento\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Novo").click()
    dropdown = self.driver.find_element(By.ID, "selGrupoSerie")
    dropdown.find_element(By.XPATH, "//option[. = 'Internos (com modelo)']").click()
    self.driver.find_element(By.ID, "selGrupoSerie").click()
    self.driver.find_element(By.ID, "txtNome").click()
    self.driver.find_element(By.ID, "txtNome").send_keys("Resposta pelo Protocolo Digital")
    self.driver.find_element(By.ID, "txaDescricao").click()
    self.driver.find_element(By.ID, "txaDescricao").send_keys("Indicado nos Parâmetros para o envio de Resposta pelo Protocolo Digital")
    dropdown = self.driver.find_element(By.ID, "selStaAplicabilidade")
    dropdown.find_element(By.XPATH, "//option[. = 'Documentos internos e externos']").click()
    self.driver.find_element(By.ID, "selStaAplicabilidade").click()
    dropdown = self.driver.find_element(By.ID, "selModelo")
    dropdown.find_element(By.XPATH, "//option[. = 'Geral_c-Num_c-Unid_s-Data_c-Int']").click()
    self.driver.find_element(By.ID, "selModelo").click()
    dropdown = self.driver.find_element(By.ID, "selStaNumeracao")
    dropdown.find_element(By.XPATH, "//option[. = 'Sequencial Anual na Unidade']").click()
    self.driver.find_element(By.ID, "selStaNumeracao").click()
    self.driver.find_element(By.NAME, "sbmCadastrarSerie").click()
  
  def test_criarTipoProcesso(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmAcessar").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Administração\"]").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Tipos de Processo\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Novo").click()
    self.driver.find_element(By.ID, "txtNome").click()
    self.driver.find_element(By.ID, "txtNome").send_keys("Protocolização de documentos para o Protocolo Central do ME")
    self.driver.find_element(By.ID, "txaDescricao").click()
    self.driver.find_element(By.ID, "txaDescricao").send_keys("Protocolização de documentos para o Protocolo Central do ME")
    self.driver.find_element(By.CSS_SELECTOR, "#fldNivelAcessoPermitido > div:nth-child(3) > div").click()
    self.driver.find_element(By.CSS_SELECTOR, "#fldNivelAcessoPermitido > div:nth-child(4) > div").click()
    self.driver.find_element(By.CSS_SELECTOR, "#fldNivelAcessoSugestao > div:nth-child(4) > div").click()
    self.driver.find_element(By.ID, "txtAssunto").click()
    self.driver.find_element(By.ID, "txtAssunto").send_keys("modernização")
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#divInfraAjaxtxtAssunto li:nth-child(1) > a")))
    element = self.driver.find_element(By.CSS_SELECTOR, "#divInfraAjaxtxtAssunto li:nth-child(1) > a")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "#selAssuntos > option")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.NAME, "sbmCadastrarTipoProcedimento").click()
  
