<?php

namespace Tests\Functional;

use Facebook\WebDriver\WebDriverBy;
use Facebook\WebDriver\WebDriverExpectedCondition;
use Facebook\WebDriver\WebDriverKeys;
use Tests\Functional\Fixtures\UsuarioRespostaFixture;


class EnviarRespostaTest extends BaseTestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function criarSistema()
    {
        $this->webDriver->get(SELENIUMTEST_SISTEMA_URL."/sip/login.php?sigla_orgao_sistema=".SELENIUMTEST_SISTEMA_ORGAO."&sigla_sistema=SEI");
        $this->webDriver->findElement(WebDriverBy::id("txtUsuario"))->sendKeys("teste");
        $this->webDriver->findElement(WebDriverBy::id("pwdSenha"))->click();
        $this->webDriver->findElement(WebDriverBy::id("pwdSenha"))->sendKeys("teste");
        $this->webDriver->findElement(WebDriverBy::id("Acessar"))->click();
        $this->webDriver->findElement(WebDriverBy::xpath("//*[text()=\"Administração\"]"))->click();
        $this->webDriver->findElement(WebDriverBy::xpath("//*[text()=\"Sistemas\"]"))->click();
        $this->webDriver->findElement(WebDriverBy::linkText("Novo"))->click();
        $dropdown = $this->webDriver->findElement(WebDriverBy::id("selOrgao"));
        $dropdown->findElement(WebDriverBy::xpath("//option[. = '".SELENIUMTEST_SISTEMA_ORGAO."']"))->click();
        $this->webDriver->findElement(WebDriverBy::id("selOrgao"))->click();
        $this->webDriver->findElement(WebDriverBy::id("txtSigla"))->click();
        $this->webDriver->findElement(WebDriverBy::id("txtSigla"))->sendKeys("PD_GOV_BR");
        $this->webDriver->findElement(WebDriverBy::id("txtNome"))->sendKeys("Protocolo Digital");
        $this->webDriver->findElement(WebDriverBy::name("sbmCadastrarSistema"))->click();
        $this->webDriver->findElement(WebDriverBy::xpath("//*[text()=\"Administração\"]"))->click();
        $this->webDriver->findElement(WebDriverBy::xpath("//*[text()=\"Sistemas\"]"))->click();
        $this->webDriver->findElement(WebDriverBy::linkText("Listar"))->click();
        $this->webDriver->findElement(WebDriverBy::xpath("//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[4]/td[6]/a[1]"))->click();
        $this->webDriver->findElement(WebDriverBy::cssSelector("#btnNovo > .infraTeclaAtalho"))->click();
        $this->webDriver->findElement(WebDriverBy::id("txtIdentificacao"))->sendKeys("SeiResposta");
        $this->webDriver->findElement(WebDriverBy::id("txtDescricao"))->sendKeys("Resposta ao protoloco digital");
        $this->webDriver->findElement(WebDriverBy::xpath("//div[@id=\'divChkSinServidor\']/div/label"))->click();
        $this->webDriver->findElement(WebDriverBy::id("txtServidor"))->click();
        $this->webDriver->findElement(WebDriverBy::id("txtServidor"))->sendKeys("*");
        $this->webDriver->findElement(WebDriverBy::id("txtServidor"))->sendKeys(WebDriverKeys::ENTER);
        $this->webDriver->findElement(WebDriverBy::name("sbmCadastrarServico"))->click();
        $this->webDriver->findElement(WebDriverBy::xpath("//img[@title=\'Operações\']"))->click();
        $this->webDriver->findElement(WebDriverBy::id("btnNovo"))->click();
        $dropdown = $this->webDriver->findElement(WebDriverBy::id("selStaOperacaoServico"));
        $dropdown->findElement(WebDriverBy::xpath("//option[. = 'Consultar Processo']"))->click();
        $this->webDriver->findElement(WebDriverBy::name("sbmCadastrarOperacaoServico"))->click();
        $this->webDriver->findElement(WebDriverBy::id("btnNovo"))->click();
        $dropdown = $this->webDriver->findElement(WebDriverBy::id("selStaOperacaoServico"));
        $dropdown->findElement(WebDriverBy::xpath("//option[. = 'Enviar Processo']"))->click();
        $this->webDriver->findElement(WebDriverBy::name("sbmCadastrarOperacaoServico"))->click();
        $this->webDriver->findElement(WebDriverBy::id("btnNovo"))->click();
        $dropdown = $this->webDriver->findElement(WebDriverBy::id("selStaOperacaoServico"));
        $dropdown->findElement(WebDriverBy::xpath("//option[. = 'Gerar Processo']"))->click();
        $this->webDriver->findElement(WebDriverBy::name("sbmCadastrarOperacaoServico"))->click();
        $this->webDriver->findElement(WebDriverBy::id("btnNovo"))->click();
        $dropdown = $this->webDriver->findElement(WebDriverBy::id("selStaOperacaoServico"));
        $dropdown->findElement(WebDriverBy::xpath("//option[. = 'Incluir Documento']"))->click();
        $this->webDriver->findElement(WebDriverBy::name("sbmCadastrarOperacaoServico"))->click();
        $this->webDriver->findElement(WebDriverBy::id("btnNovo"))->click();
        $dropdown = $this->webDriver->findElement(WebDriverBy::id("selStaOperacaoServico"));
        $dropdown->findElement(WebDriverBy::xpath("//option[. = 'Consultar Documento']"))->click();
        $this->webDriver->findElement(WebDriverBy::name("sbmCadastrarOperacaoServico"))->click();
        $this->webDriver->findElement(WebDriverBy::id("btnFechar"))->click();
        $this->webDriver->findElement(WebDriverBy::id("btnFechar"))->click();
    }

    public function criarTipoProcesso()
    {
        $this->acessarSistema('localhost:8000/sei', 'teste', 'teste');
        $this->webDriver->findElement(WebDriverBy::xpath("//*[text()=\"Administração\"]"))->click();
        $this->webDriver->findElement(WebDriverBy::xpath("//*[text()=\"Tipos de Processo\"]"))->click();
        $this->webDriver->findElement(WebDriverBy::linkText("Novo"))->click();
        $this->webDriver->findElement(WebDriverBy::id("txtNome"))->click()
            ->sendKeys("Protocolização de documentos para o Protocolo Central do ME");
        $this->webDriver->findElement(WebDriverBy::id("txaDescricao"))->click()
            ->sendKeys("Protocolização de documentos para o Protocolo Central do ME");
        $this->webDriver->findElement(WebDriverBy::cssSelector("#divSinRestritoPermitido .infraCheckboxLabel"))
            ->click();
        $this->webDriver->findElement(WebDriverBy::cssSelector("#divOptPublicoSugestao .infraRadioLabel"))
            ->click();
        $this->webDriver->findElement(WebDriverBy::id("txtAssunto"))->click()
            ->sendKeys("modernização");
        $this->webDriver->wait(30)
            ->until(
                WebDriverExpectedCondition::visibilityOfAnyElementLocated(
                    WebDriverBy::cssSelector("#divInfraAjaxtxtAssunto li:nth-child(1) > a")
                )
            );
        $element = $this->webDriver
            ->findElement(WebDriverBy::cssSelector("#divInfraAjaxtxtAssunto li:nth-child(1) > a"));
        $this->webDriver->action()->moveToElement($element)->clickAndHold()->perform();
        $element = $this->webDriver
            ->findElement(WebDriverBy::cssSelector("#selAssuntos > option"));
        $this->webDriver->action()->moveToElement($element)->clickAndHold()->perform();
        $this->webDriver->findElement(WebDriverBy::cssSelector( "body"))->click();
        $this->webDriver->findElement(WebDriverBy::name("sbmCadastrarTipoProcedimento"))->click();
    }

    public function criarConfiguracao()
    {

    }

    public function test_enviar_resposta_definitiva()
    {
        $this->createEnvironment();

        $this->assertTrue(true);
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
