# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test00SEIRespostaCriarSistema():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://seleniumhub:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_criarSistema(self):
    self.driver.get("http://sei.resposta.nuvem.gov.br//sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[1]/a").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Sistemas\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Novo").click()
    dropdown = self.driver.find_element(By.ID, "selOrgao")
    dropdown.find_element(By.XPATH, "//option[. = 'ME']").click()
    self.driver.find_element(By.ID, "selOrgao").click()
    self.driver.find_element(By.ID, "txtSigla").click()
    self.driver.find_element(By.ID, "txtSigla").send_keys("PD_GOV_BR")
    self.driver.find_element(By.ID, "txtNome").send_keys("Protocolo Digital")
    self.driver.find_element(By.NAME, "sbmCadastrarSistema").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[1]/a").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Sistemas\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Listar").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[4]/td[6]/a[1]").click()
    self.driver.find_element(By.CSS_SELECTOR, "#btnNovo > .infraTeclaAtalho").click()
    self.driver.find_element(By.ID, "txtIdentificacao").send_keys("SeiResposta")
    self.driver.find_element(By.ID, "txtDescricao").send_keys("Resposta ao protoloco digital")
    self.driver.find_element(By.ID, "txtServidor").click()
    self.driver.find_element(By.ID, "txtServidor").send_keys("*")
    self.driver.find_element(By.ID, "txtServidor").send_keys(Keys.ENTER)
    self.driver.find_element(By.NAME, "sbmCadastrarServico").click()
    self.driver.find_element(By.ID, "btnFechar").click()
  
  def test_criarTipoDocumento(self):
    self.driver.get("http://sei.resposta.nuvem.gov.br//sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[1]/a").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Tipos de Documento\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Novo").click()
    dropdown = self.driver.find_element(By.ID, "selGrupoSerie")
    dropdown.find_element(By.XPATH, "//option[. = 'Internos (com modelo)']").click()
    self.driver.find_element(By.ID, "selGrupoSerie").click()
    self.driver.find_element(By.ID, "txtNome").click()
    self.driver.find_element(By.ID, "txtNome").send_keys("Resposta ao Protocolo Digital")
    self.driver.find_element(By.ID, "txaDescricao").click()
    self.driver.find_element(By.ID, "txaDescricao").send_keys("Indicado nos Parâmetros para o envio de Resposta ao Protocolo Digital")
    dropdown = self.driver.find_element(By.ID, "selStaAplicabilidade")
    dropdown.find_element(By.XPATH, "//option[. = 'Documentos internos e externos']").click()
    self.driver.find_element(By.ID, "selStaAplicabilidade").click()
    dropdown = self.driver.find_element(By.ID, "selModelo")
    dropdown.find_element(By.XPATH, "//option[. = 'Geral_c-Num_c-Unid_s-Data_c-Int']").click()
    self.driver.find_element(By.ID, "selModelo").click()
    dropdown = self.driver.find_element(By.ID, "selStaNumeracao")
    dropdown.find_element(By.XPATH, "//option[. = 'Sequencial Anual na Unidade']").click()
    self.driver.find_element(By.ID, "selStaNumeracao").click()
    self.driver.find_element(By.ID, "chkSinInteressado").click()
    self.driver.find_element(By.NAME, "sbmCadastrarSerie").click()
  
  def test_criarTipoProcesso(self):
    self.driver.get("http://sei.resposta.nuvem.gov.br//sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[1]/a").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Tipos de Processo\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Novo").click()
    self.driver.find_element(By.ID, "txtNome").click()
    self.driver.find_element(By.ID, "txtNome").send_keys("Protocolização de documentos para o Protocolo Central do ME")
    self.driver.find_element(By.ID, "txaDescricao").click()
    self.driver.find_element(By.ID, "txaDescricao").send_keys("Protocolização de documentos para o Protocolo Central do ME")
    self.driver.find_element(By.ID, "chkSinRestritoPermitido").click()
    self.driver.find_element(By.ID, "chkSinPublicoPermitido").click()
    self.driver.find_element(By.ID, "optPublicoSugestao").click()
    self.driver.find_element(By.ID, "txtAssunto").click()
    self.driver.find_element(By.ID, "txtAssunto").send_keys("modernização")
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#divInfraAjaxtxtAssunto li:nth-child(1) > a")))
    element = self.driver.find_element(By.CSS_SELECTOR, "#divInfraAjaxtxtAssunto li:nth-child(1) > a")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "#selAssuntos > option")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.NAME, "sbmCadastrarTipoProcedimento").click()
  
